#!/system/bin/sh
#PROJECT DARK BOOSTER - ABS Tweaks
#Version - 4.1
#Devoloped by dark_optimistic @XDA
#Copyright (C)2015 dark_optimistic
#***********************************************************************#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#***********************************************************************#



mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system



busybox sleep 10

path=`busybox ls -d /sys/block/* 2>/dev/null`;
for S in $path;
do
	if [ -e $S/queue/rotational ]; then
		busybox echo "0" > $S/queue/rotational;
	fi;
	if [ -e $S/queue/iostats ]; then
		busybox echo "0" > $S/queue/iostats;
	fi;
	if [ -e $S/queue/nr_requests ]; then
		busybox echo "1024" > $S/queue/nr_requests;
	fi;
	if [ -e $S/queue/nomerges ]; then
		busybox echo "1" > $S/queue/nomerges;
	fi;	
	
done

